# -*- coding: utf-8 -*-
"""fpp_speedup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QPQgZDBnz3GseyQE-eVJZFnKNIca-h9G
"""

# Commented out IPython magic to ensure Python compatibility.
# importing the required libraries
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
#nqueens
seq_q = np.repeat(12594.511,7)
x = np.array([1, 2,4,8,16,32,64]) 
y_q = np.array([13720.909,7739.592,6012.657,8224.159,7685.270,7917.274,8291.606])
#sor
seq_sor = np.repeat(91566.732,7)
y_sor = np.array([91907.977,46611.836,23968.717,12395.079,7657.805,4571.791,3379.277])
#heat
seq_heat = np.repeat(127121.093,7)
y_heat = np.array([126450.956,65847.052,33203.517,17595.325,19180.050,12056.474,9351.539])
plt.plot(x, seq_q/y_q,marker='.')
plt.plot(x, seq_sor/y_sor,marker='.')
plt.plot(x,seq_heat/y_heat,marker='.')
plt.legend(['nqueens','SOR','HEAT'])
plt.title("COTTON_LACE speedup")
plt.xlabel("no of cores")
plt.ylabel("speedup")
plt.show()

#COTTON_LACE 32
avg_nqueens_cl = (7941.814+7942.802+7984.132+8042.731+7959.305)/5
avg_sor_cl = (4580.899+4467.833+4621.157+4784.601+4630.956)/5
avg_heat_cl = (13295.764+12131.153+13133.887+12704.490+12407.318)/5
#COTTON 32
avg_nqueens_c= (9140.946+8919.680+9050.692+8894.997+8994.113)/5
avg_sor_c = (4671.300+4574.669+4556.866+4573.792+4807.843)/5
avg_heat_c = (13777.379+13705.385+12498.065+13794.728+12223.278)/5
#HCLIB 32
avg_nqueens_h = (5190.490+4775.873+5030.384+4814.600+4899.472)/5
avg_sor_h = (4805.640+4684.613+5065.883+5003.031+4938.795)/5
avg_heat_h = (12009.193+12738.605+12858.484+13472.672+12746.733)/5

#nqueens
runtime = ['cotton_lace','cotton++','hclib']
speedup= [12594.511/avg_nqueens_cl,12594.511/avg_nqueens_c,12594.511/avg_nqueens_h]
fig = plt.figure(figsize =(3, 3))
plt.xlabel("Runtime")
plt.ylabel("Speedup")
plt.title("32 cores NQueens")
plt.bar(runtime,speedup,width=0.4)

#SOR
speedup= [91566.732/avg_sor_cl,91566.732/avg_sor_c,91566.732/avg_sor_h]
fig = plt.figure(figsize =(3, 3))
plt.xlabel("Runtime")
plt.ylabel("Speedup")
plt.title("32 cores SOR")
plt.bar(runtime,speedup,width=0.4)
print(speedup)

#HEAT
speedup= [127121.093/avg_heat_cl,127121.093/avg_heat_c,127121.093/avg_heat_h]
fig = plt.figure(figsize =(3, 3))
plt.xlabel("Runtime")
plt.ylabel("Speedup")
plt.title("32 cores HEAT")
plt.bar(runtime,speedup,width=0.4)
print(speedup)